#' @title Plot of the predictions in silver eel migration
#'
#' @description This function plot the predictions of silver eel migration based on an ensemble of generalized boosted models.
#'
#' @param pred a data.frame object generated by the function \code{predict_silver} or \code{predict_silver_all}.
#' @param bio_year the year of the migration season. If \code{bio_year="last"} (default parameter), the last year of migration is used.
#' @param intensity a character vector specifying the migration class, should be \code{"P50"}, \code{"P75"} or \code{"P95"},
#' @param hard_pred logical. If \code{TRUE}, the hard predictions are included in the graph.
#'
#'
#' @return NULL
#'
#' @examples
#' # extracts hydrological predictors for the Elorn River
#' hydro_elorn <- extract_hydro(date = elorn_sub$date, quse = elorn_sub$Q,
#' Qlim_class = c(1.31,1.65,2.06,2.7,3.52,4.63,6.09,8.47,12.7,28.9))
#' # select river references (all without the Elorn River)
#' river_used <- c("Aulne", "Dordogne", "Loire", "Meuse", "Oir",
#' "Orne", "Scorff", "Sevre", "Touques")
#' # predicts the eel migration for all classes based on weighted predictions
#' pred_size_all <- predict_silver_all(newtab = hydro_elorn, river_ref=river_used,
#' weightsuse = "log_size", new_size=260)
#'
#' # plot migration predictions for 2018 (similar to bio_year = "last")
#' plot_silver(pred = pred_size_all, bio_year = 2018)
#'
#'
#'
#' @export
#'
plot_silver <- function(pred, bio_year="last", intensity=c("P50", "P75", "P95"), hard_pred=TRUE){
  if(bio_year=="last") {bio_year <- max(pred$bio_year)}
  datause <- pred[pred$bio_year==bio_year,]
  datause$date <- as.Date(datause$date)
  Qmodif<-datause$Q/max(datause$Q, na.rm=T)
  prob_ok <- intensity[paste0("prob_", intensity) %in% names(datause)]
  graphics::par(mar=c(5.1, 4.1, 4.1, 4.1))
  graphics::plot(datause$date, Qmodif,type="n", ylim=c(0,1), ylab="Probability of silver eel migration", xlab="Date", las=1)
  if("P95" %in% prob_ok) { graphics::polygon(c(min(datause$date),datause$date, max(datause$date)), c(0,datause$prob_P95,0),
                                             col= '#fee6ce', border="NA" ) }
  if("P75" %in% prob_ok) { graphics::polygon(c(min(datause$date),datause$date, max(datause$date)), c(0,datause$prob_P75,0),
                                             col= '#fdae6b', border="NA" ) }
  if("P50" %in% prob_ok) { graphics::polygon(c(min(datause$date),datause$date, max(datause$date)), c(0,datause$prob_P50,0),
                                             col= '#fb6a4a' , border="NA" ) }
  graphics::points(datause$date, Qmodif, type="l", lwd=1.3, lty=1, col="#045a8d")
  prQ <- pretty(range(datause$Q))
  graphics::axis(side=4, at = prQ/max(datause$Q, na.rm=T), prQ, las=1)
  graphics::mtext("River discharge", side=4,  line = 2, las=3)
  cool <- c("#fee6ce","#fdae6b","#fb6a4a") ; names(cool) <- c("P95", "P75", "P50")
  graphics::legend("topleft",prob_ok, cex=0.6,  col=cool[prob_ok], lty=1, lwd=4, title = "Peak intensities")
  graphics::abline(h=0.5, lty=2, lwd =0.8)
  if(hard_pred==TRUE){
    hard_col <- rep(NA, nrow(datause))
    if("P95" %in% prob_ok) { hard_col <- ifelse(datause$mig_P95, "#fee6ce", hard_col) }
    if("P75" %in% prob_ok) { hard_col <- ifelse(datause$mig_P75, "#fdae6b", hard_col) }
    if("P50" %in% prob_ok) { hard_col <- ifelse(datause$mig_P50, "#fb6a4a", hard_col) }
    graphics::points(datause$date, rep(0.95, length(datause$date)), pch=15, col=as.character(hard_col))
  }
}



