#' @title Predict the migration of silver eels based on hydrological predictors
#'
#' @description This function uses hydrological predictors for predicting the silver eel migration based on an ensemble of generalized boosted models.
#'
#' @param newtab a data.frame object generated by the function \code{extract_hydro}.
#' @param river_ref a character vector specifying the names of river references used to make predictions. If \code{river_ref="all"} (default parameter), the ten river references are used in the prediction process \emph{(i.e. Aulne, Dordogne, Elorn, Loire, Meuse, Oir, Orne, Scorff, Sevre, Touques)}.
#' @param intensity a character specifying the migration class, should be \code{"P50"}, \code{"P75"} or \code{"P95"},
#' @param weightsuse a numeric vector of the same length as \code{river_ref} used for models weighting. If \code{weightsuse} is \code{"equal"} the average of predictions of models is returned. If \code{weightsuse} is \code{"log_size"} different weights are applied to predictions depending on dissimilarities in catchment sizes (see Details).
#' @param new_size a numeric value specifying the catchment area (km²) of the new river. Is mandatory if \code{weightsuse="log_size"},
#' @param plim a numeric threshold value for the hard predictions (default \code{plim = 0.5}).
#'
#' @details When \code{weightsuse} is \code{"log_size"} the predictions are weighted by the differences in log-transformed areas of catchments. The weighting formula gives twice as much importance to the most similar site as to the most different site for producing the final predictions (see Teichert et al.).
#'
#' @return A data.frame with probabilities of silver eel migration according to the river hydrological conditions.
#' \itemize{
#'   \item date : the date,
#'   \item Q : the river discharge,
#'   \item bio_year : the migration season,
#'   \item n_models : the number of models used to make the prediction,
#'   \item prop : the probability of silver eel migration,
#'   \item mig : the hard prediction for silver eel migration.
#' }
#'
#' @rdname funs
#' @examples
#' # extracts hydrological predictors for the Elorn River
#' hydro_elorn <- extract_hydro(date = elorn_sub$date, quse = elorn_sub$Q,
#' Qlim_class = c(1.31,1.65,2.06,2.7,3.52,4.63,6.09,8.47,12.7,28.9))
#' # select river references (all without the Elorn River)
#' river_used <- c("Aulne", "Dordogne", "Loire", "Meuse", "Oir",
#' "Orne", "Scorff", "Sevre", "Touques")
#'
#' # predicts the eel migration for P50 based on averaged predictions
#' pred_equal <- predict_silver(newtab = hydro_elorn, river_ref=river_used,
#' intensity="P50", weightsuse = "equal")
#' # predicts the eel migration for P50 based on size weighted predictions
#' pred_size <- predict_silver(newtab = hydro_elorn, river_ref=river_used,
#' intensity="P50", weightsuse = "log_size", new_size=260)
#'
#' # predicts the eel migration for all classes based on size weighted predictions
#' pred_size_all <- predict_silver_all(newtab = hydro_elorn, river_ref=river_used,
#' weightsuse = "log_size", new_size=260)
#'
#'
#' @export
predict_silver <- function(newtab, river_ref, intensity, weightsuse="equal", new_size=NULL, plim=0.5) {
  normalized <- function(x) (min(x)-x)/(max(x)-min(x)) + 2
  try(if(weightsuse=="log_size" & is.null(new_size)) stop("new_size is empty with no default value for areas weighted predictions"))
  train_date <- newtab$date
  if(river_ref[1]=="all") {river_ref <- c("Aulne", "Dordogne", "Elorn", "Loire", "Meuse", "Oir", "Orne", "Scorff", "Sevre", "Touques") }
  selmod <- paste0(intensity, "_", river_ref)
  pred_val <- numeric()
  for(i in 1:length(selmod)){
    model_to_use <- get(selmod[i])
    pred_val <- cbind(pred_val, gbm::predict.gbm(object=model_to_use, newdata=newtab, n.trees = model_to_use$best, type="response"))
  }
  if(weightsuse=="equal") {w0 <- rep(1, ncol(pred_val))}
  if(weightsuse=="log_size"){ diff_size <- abs(log(silvRpeak::river_features[river_ref, "catchment"]) - log(new_size)) ; w0 <- normalized(diff_size) }
  w<-matrix(w0, ncol=length(w0), nrow=nrow(pred_val), byrow=T)
  n_models<-rowSums(ifelse(is.na(pred_val),0,1),na.rm=T)
  w<-ifelse(is.na(pred_val),0,w)
  w<-w/rowSums(w)
  prop_w <- rowSums(pred_val*w, na.rm = TRUE)
  resp <- ifelse(prop_w>plim, 1, 0)
  pred <- data.frame(date=train_date, bio_year=newtab$bio_year, Q=newtab$Q, n_models, prob=round(prop_w,4), mig=resp)
  names(pred)[c(5:6)]<-paste0(names(pred)[c(5:6)], "_", intensity)
  pred
}

#' @rdname funs
#' @examples
#' # predicts the eel migration for all classes based on size weighted predictions
#' pred_size_all <- predict_silver_all(newtab = hydro_elorn, river_ref=river_used,
#' weightsuse = "log_size", new_size=260)
#'
#' @export
predict_silver_all <- function(newtab, river_ref, weightsuse="equal", new_size=NULL, plim=0.5){
  try(if(weightsuse=="log_size" & is.null(new_size)) stop("new_size is empty with no default value for areas weighted predictions"))
  pred_P50 <- predict_silver(newtab, river_ref, weightsuse, new_size, intensity="P50", plim)
  pred_P75 <- predict_silver(newtab, river_ref, weightsuse, new_size, intensity="P75", plim)
  pred_P95 <- predict_silver(newtab, river_ref, weightsuse, new_size, intensity="P95", plim)
  pred_compil <- merge(pred_P50, pred_P75[, c(1,5,6)], by="date")
  pred_compil <- merge(pred_compil, pred_P95[, c(1,5,6)], by="date")
  pred_compil
}
